### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'alfred_data_all/json_2.1.0/trial_T20190906_190741_530882/pp/ann_0.json'

### ISSUE THREAD

**Issue by TopCoder2K** [soyeonm/FILM#9]
When I finished setting up FILM using the instruction in the README and tried to run
```
python main.py  -n1 --max_episode_length 1000 --num_local_steps 25  --num_processes 1 --eval_split tests_unseen --from_idx 0 --to_idx 120 --x_display 0  --max_fails 10  --debug_local --learned_depth  --use_sem_seg --which_gpu 0 --sem_gpu_id 0 --sem_seg_gpu 0 --depth_gpu 0 --set_dn first_run   --use_sem_policy  --save_pictures
```
I got
```
Process ForkServerProcess-1:
Traceback (most recent call last):
  File "/home/pchelintsev/FILM/agents/sem_exp_thor.py", line 135, in load_initial_scene
    traj_data = self.load_traj(self.scene_names[self.scene_pointer]); r_idx = self.scene_names[self.scene_pointer]['repeat_idx']
  File "/home/pchelintsev/FILM/agents/sem_exp_thor.py", line 84, in load_traj
    traj_data = json.load(open(json_dir))
FileNotFoundError: [Errno 2] No such file or directory: 'alfred_data_all/json_2.1.0/trial_T20190906_190741_530882/pp/ann_0.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pchelintsev/.conda/envs/film/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/pchelintsev/.conda/envs/film/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pchelintsev/FILM/envs/utils/vector_env.py", line 222, in _worker_env
    obs, info, actions_dict = env.load_initial_scene()
  File "/home/pchelintsev/FILM/agents/sem_exp_thor.py", line 187, in load_initial_scene
    obs = np.zeros(self.obs.shape)
AttributeError: 'NoneType' object has no attribute 'shape'
Traceback (most recent call last):
  File "main.py", line 831, in <module>
    main()
  File "main.py", line 121, in main
    obs, infos, actions_dicts = envs.load_initial_scene()
  File "/home/pchelintsev/FILM/envs/__init__.py", line 71, in load_initial_scene
    obs, info, actions_dict = self.venv.load_initial_scene()
  File "/home/pchelintsev/FILM/envs/utils/vector_env.py", line 475, in load_initial_scene
    results.append(read_fn())
  File "/home/pchelintsev/.conda/envs/film/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/pchelintsev/.conda/envs/film/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/pchelintsev/.conda/envs/film/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Exception ignored in: <function VectorEnv.__del__ at 0x7efd221b6560>
Traceback (most recent call last):
  File "/home/pchelintsev/FILM/envs/utils/vector_env.py", line 767, in __del__
    self.close()
  File "/home/pchelintsev/FILM/envs/utils/vector_env.py", line 564, in close
    read_fn()
  File "/home/pchelintsev/.conda/envs/film/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/pchelintsev/.conda/envs/film/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/pchelintsev/.conda/envs/film/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError:
```

It seems to be due to the creation of an inappropriate symbolic link:
```
cd $FILM
mkdir alfred_data_all 
ln -s $ALFRED_ROOT/data/json_2.1.0 $FILM/alfred_data_all
```
as I can't find `pp` folder inside `json_2.1.0` (the preprocessing used `json_feat_2.1.0`) but I cant find the preprocessed jsons in `json_feat_2.1.0/task_name/pp/`. Should I then create the symlink for `$ALFRED_ROOT/data/json_feat_2.1.0`?

**Comment by TopCoder2K** [comment]
Hmm, it looks like the best solution for this is offered [here](https://github.com/soyeonm/FILM/issues/2#issue-1188383110). It's necessary to use `--data data/json_2.1.0`, not `--data data/json_feat_2.1.0`, then the preprocessed files are saved in `json_2.1.0` and the symlink works as expected
